<a href="https://colab.research.google.com/github/valentintesta/Python_DataAnalytics1/blob/main/Web_Scrapping_Python1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Importar Librerias
import pandas as pd
import requests
!pip install alphacast
from alphacast import Alphacast

Collecting alphacast
  Downloading alphacast-0.1.7-py3-none-any.whl (5.0 kB)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from alphacast) (2.31.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from alphacast) (1.5.3)
Collecting python-dotenv (from alphacast)
  Downloading python_dotenv-1.0.0-py3-none-any.whl (19 kB)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas->alphacast) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->alphacast) (2023.3)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas->alphacast) (1.23.5)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->alphacast) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->alphacast) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->alphacast) (2.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->alphacast) (2023.7.22)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas->alphacast) (1.16.0)
Installing collected packages: python-dotenv, alphacast
Successfully installed alphacast-0.1.7 python-dotenv-1.0.0

In [2]:
#Data Freme
#Creamos el dataframe a partir del archivo csv
df = pd.read_csv("/precios-de-gas-natural-.csv")
df.head()

,id_pub,anio,mes,cuenca,contrato,precio_distribuidora,precio_gnc,precio_usina,precio_industria,precio_otros,precio_ppp,precio_expo,indice_tiempo
0,1,2019,1,Austral Santa Cruz,FIRME,3.56,3.43,3.10,3.27,3.75,3.30,2.00,2019-01
1,2,2019,1,Austral Santa Cruz,INTERRUMPIBLE,3.04,3.54,2.29,2.38,0.00,2.39,3.25,2019-01
2,3,2019,1,Austral Santa Cruz,TOTAL,3.40,3.44,2.65,3.13,3.75,3.03,3.08,2019-01
3,4,2019,1,Austral Tierra del Fuego,FIRME,3.66,3.33,3.30,3.39,0.00,3.45,0.00,2019-01
4,5,2019,1,Austral Tierra del Fuego,INTERRUMPIBLE,3.43,0.00,2.33,2.28,0.00,2.37,3.49,2019-01

In [3]:
#Borramos las filas y columnas completamente vacias
df.dropna(how= "all" , axis = 1 )
df.dropna(how= "all" , axis = 0 )

,id_pub,anio,mes,cuenca,contrato,precio_distribuidora,precio_gnc,precio_usina,precio_industria,precio_otros,precio_ppp,precio_expo,indice_tiempo
0,1,2019,1,Austral Santa Cruz,FIRME,3.56,3.43,3.10,3.27,3.75,3.30,2.00,2019-01
1,2,2019,1,Austral Santa Cruz,INTERRUMPIBLE,3.04,3.54,2.29,2.38,0.00,2.39,3.25,2019-01
2,3,2019,1,Austral Santa Cruz,TOTAL,3.40,3.44,2.65,3.13,3.75,3.03,3.08,2019-01
3,4,2019,1,Austral Tierra del Fuego,FIRME,3.66,3.33,3.30,3.39,0.00,3.45,0.00,2019-01
4,5,2019,1,Austral Tierra del Fuego,INTERRUMPIBLE,3.43,0.00,2.33,2.28,0.00,2.37,3.49,2019-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...
967,968,2023,6,Noroeste,INTERRUMPIBLE,0.00,3.39,3.08,5.20,0.00,3.48,0.00,2023-06
968,969,2023,6,Noroeste,TOTAL,0.00,3.63,3.08,5.91,0.00,4.97,0.00,2023-06
969,970,2023,6,Total Cuenca,FIRME,2.82,3.21,4.32,4.48,0.00,3.66,7.72,2023-06
970,971,2023,6,Total Cuenca,INTERRUMPIBLE,11.67,2.88,3.80,3.78,3.00,3.67,7.74,2023-06
971,972,2023,6,Total Cuenca,TOTAL,2.82,3.14,4.26,4.42,3.00,3.66,7.73,2023-06

In [4]:
#Ahora nos quedamos con los datos de cuenca, Austral Tierra del Fuego
df = df[df["cuenca"]== "Austral Tierra del Fuego"]
df.head()

,id_pub,anio,mes,cuenca,contrato,precio_distribuidora,precio_gnc,precio_usina,precio_industria,precio_otros,precio_ppp,precio_expo,indice_tiempo
3,4,2019,1,Austral Tierra del Fuego,FIRME,3.66,3.33,3.30,3.39,0.0,3.45,0.00,2019-01
4,5,2019,1,Austral Tierra del Fuego,INTERRUMPIBLE,3.43,0.00,2.33,2.28,0.0,2.37,3.49,2019-01
5,6,2019,1,Austral Tierra del Fuego,TOTAL,3.66,3.33,2.81,3.36,0.0,3.19,3.49,2019-01
21,22,2019,2,Austral Tierra del Fuego,FIRME,3.65,3.19,3.00,3.50,0.0,3.36,0.00,2019-02
22,23,2019,2,Austral Tierra del Fuego,INTERRUMPIBLE,3.52,0.00,2.15,2.52,0.0,2.23,3.22,2019-02

In [5]:
#Ahora nos quedamos con los datos de cuenca, Austral Tierra del Fuego
df = df[df["cuenca"]== "Austral Tierra del Fuego"]
df.head()

,id_pub,anio,mes,cuenca,contrato,precio_distribuidora,precio_gnc,precio_usina,precio_industria,precio_otros,precio_ppp,precio_expo,indice_tiempo
3,4,2019,1,Austral Tierra del Fuego,FIRME,3.66,3.33,3.30,3.39,0.0,3.45,0.00,2019-01
4,5,2019,1,Austral Tierra del Fuego,INTERRUMPIBLE,3.43,0.00,2.33,2.28,0.0,2.37,3.49,2019-01
5,6,2019,1,Austral Tierra del Fuego,TOTAL,3.66,3.33,2.81,3.36,0.0,3.19,3.49,2019-01
21,22,2019,2,Austral Tierra del Fuego,FIRME,3.65,3.19,3.00,3.50,0.0,3.36,0.00,2019-02
22,23,2019,2,Austral Tierra del Fuego,INTERRUMPIBLE,3.52,0.00,2.15,2.52,0.0,2.23,3.22,2019-02

In [6]:
#Creamos una nueva columna llamada country que luego sera declarada como entity
df["country"] = "Argentina"

In [7]:
#Creamos la columna Date que la usamos como index
df["Date"] = pd.to_datetime(df["indice_tiempo"], format = "%Y-%m")
df.set_index("Date", inplace= True)
df

,id_pub,anio,mes,cuenca,contrato,precio_distribuidora,precio_gnc,precio_usina,precio_industria,precio_otros,precio_ppp,precio_expo,indice_tiempo,country
Date,,,,,,,,,,,,,,
2019-01-01,4,2019,1,Austral Tierra del Fuego,FIRME,3.66,3.33,3.30,3.39,0.0,3.45,0.00,2019-01,Argentina
2019-01-01,5,2019,1,Austral Tierra del Fuego,INTERRUMPIBLE,3.43,0.00,2.33,2.28,0.0,2.37,3.49,2019-01,Argentina
2019-01-01,6,2019,1,Austral Tierra del Fuego,TOTAL,3.66,3.33,2.81,3.36,0.0,3.19,3.49,2019-01,Argentina
2019-02-01,22,2019,2,Austral Tierra del Fuego,FIRME,3.65,3.19,3.00,3.50,0.0,3.36,0.00,2019-02,Argentina
2019-02-01,23,2019,2,Austral Tierra del Fuego,INTERRUMPIBLE,3.52,0.00,2.15,2.52,0.0,2.23,3.22,2019-02,Argentina
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-05-01,941,2023,5,Austral Tierra del Fuego,INTERRUMPIBLE,0.00,0.00,3.93,5.37,0.0,4.37,0.00,2023-05,Argentina
2023-05-01,942,2023,5,Austral Tierra del Fuego,TOTAL,3.10,3.42,3.89,5.49,0.0,3.80,0.00,2023-05,Argentina
2023-06-01,958,2023,6,Austral Tierra del Fuego,FIRME,2.90,3.26,3.87,6.58,0.0,3.80,0.00,2023-06,Argentina
2023-06-01,959,2023,6,Austral Tierra del Fuego,INTERRUMPIBLE,0.00,0.00,3.88,4.63,0.0,4.11,0.00,2023-06,Argentina
2023-06-01,960,2023,6,Austral Tierra del Fuego,TOTAL,2.90,3.26,3.87,6.22,0.0,3.83,0.00,2023-06,Argentina